### ISSUE TITLE
Wrong explanaiton of argument `icon` of setCaption

### ISSUE THREAD

**Issue by yhara** [ohai/rubysdl#5]
https://www.kmc.gr.jp/~ohai/rubysdl_ref_2.en.html#label-293 says:

```
SDL::WM.set_caption(title, icon)
SDL::WM.setCaption(title, icon)
Sets the title-bar and icon name of the display window.
```

But according to http://sdl.beuc.net/sdl.wiki/SDL_WM_SetCaption , `icon` specifies iconified window title, not icon name.

**Comment by ohai** [comment]
Todo: Update website
